Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group for my EC2 instance"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0c94855ba95c71c99"
      InstanceType: "t2.micro"
      KeyName: "mykey"
      SecurityGroupIds:
        - !Ref SecurityGroup

  KeyPair:
    Type: "AWS::EC2::KeyPair"
    Properties:
      KeyName: "mykey"
